### ISSUE TITLE
Functions ReadFloat and ReadInt64 don't compile in Delphi < 10.3 / 10.4

### ISSUE THREAD

**Issue by mzwolsky** [paolo-rossi/delphi-neon#47]
The functions **TNeonDeserializerJSON.ReadFloat** and **TNeonDeserializerJSON.ReadInt64** in the _Source/Neon.Core.Persistence.JSON.pas_ cause compilation errors in my Delphi version 10.2.

As it turns out `System.JSON.TJSONNumber.AsType<T>` (line 1523) is only supported from Delphi versions 10.3 up.
See https://docwiki.embarcadero.com/Libraries/Tokyo/en/System.JSON.TJSONNumber_Methods and https://docwiki.embarcadero.com/Libraries/Rio/en/System.JSON.TJSONNumber_Methods

And `System.Rtti.TValue.Make<T>` (line 1553) is only supported from Delphi 10.4 up.
See https://docwiki.embarcadero.com/Libraries/Rio/en/System.Rtti.TValue.Make and https://docwiki.embarcadero.com/Libraries/Sydney/en/System.Rtti.TValue.Make

Best regards,
Marcus
